### PR TITLE
Removed Members section and Member Modals in <footer />

### PR DESCRIPTION
**Pull request by sudheerdarla**
Removed Members section

### CODE REVIEW

**Comment by vramana** [comment]
Rather than commenting out. Just remove the whole thing.

**Comment by vramana** [comment]
Also below `<footer>` There is some code  for member modals. Can you also remove that?

**Comment by sudheerdarla** [comment]
done

**Comment by vramana** [comment]
Can you squash all the commits? If you need help ping me in gitter.

**Comment by sudheerdarla** [comment]
I dont know squashing. sorry..will learn it

**Comment by vramana** [comment]
Closing this since we have changed things in the latest master

**Pull request closed without merging**
