### PR TITLE
added sudheerdarla profile and made some changes

### PR DESCRIPTION
**Pull request by sudheerdarla**

### CODE REVIEW

**Comment by duttakapil** [comment]
Hey @sudheerdarla, so I accepted @srichakradhar 's PR before yours and now there is merge conflict in the members list index.html. You need to move your list item after Chuck's and then push again. Got it?

**Comment by sudheerdarla** [comment]
Got it kapil!

**Comment by duttakapil** [comment]
No worries, I resolved and added your changes

**Comment by sudheerdarla** [comment]
And I also pushed to my fork.

**Pull request merged**
